name: "Scorecard"
on:
  branch_protection_rule:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: ["main", "1.26.x"]

permissions: read-all

jobs:
  analysis:
    name: "Scorecard"
    runs-on: "ubuntu-latest"
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
    
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c"
        with:
          persist-credentials: false

      - name: "Run Scorecard"
        uses: "ossf/scorecard-action@99c53751e09b9529366343771cc321ec74e9bd3d"
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
          publish_results: true
